# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd41375f1a5c337388ce9843407acae29ce106ba4b37d1436778888c7398d69dcac18c7e3ae02ee4c7d66eeac207cad4872ba9bd5e48a189d3a37c450ed3e49

test:
  secret_key_base: 598d3d3710b0ed95d2bed7d2e25f3c807a1102e984ec0c86cb8cb10730e68ff3ea9598941da1123dda225e74f5f21adedf9c2d1852afcde7ba90c2c47a655775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
